// <auto-generated />
using LabbASPclient.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabbASPclient.Migrations
{
    [DbContext(typeof(LagerContext))]
    [Migration("20210121105751_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("LabbASPclient.Models.Artiklar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Antal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pris")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Produktbeskrivning")
                        .HasColumnType("TEXT");

                    b.Property<string>("Produktnamn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tillverkare")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artiklars");
                });
#pragma warning restore 612, 618
        }
    }
}
