// <auto-generated />
using LabbASPclient.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabbASPclient.Migrations
{
    [DbContext(typeof(LagerContext))]
    partial class LagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("LabbASPclient.Models.Artiklar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Antal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pris")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Produktbeskrivning")
                        .HasColumnType("TEXT");

                    b.Property<string>("Produktnamn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tillverkare")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Artiklars");
                });

            modelBuilder.Entity("LabbASPclient.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kategorinamn")
                        .HasColumnType("TEXT");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategoris");
                });

            modelBuilder.Entity("LabbASPclient.Models.Artiklar", b =>
                {
                    b.HasOne("LabbASPclient.Models.Kategori", "Kategorinamn")
                        .WithMany("Artiklars")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorinamn");
                });

            modelBuilder.Entity("LabbASPclient.Models.Kategori", b =>
                {
                    b.Navigation("Artiklars");
                });
#pragma warning restore 612, 618
        }
    }
}
