// <auto-generated />
using CoreDBAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreDBAPI.Migrations
{
    [DbContext(typeof(LagerContext))]
    [Migration("20210121173801_Kategori")]
    partial class Kategori
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CoreDBAPI.Model.Artiklar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("Pris")
                        .HasColumnType("int");

                    b.Property<string>("Produktbeskrivning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produktnamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tillverkare")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Artiklars");
                });

            modelBuilder.Entity("CoreDBAPI.Model.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Kategorinamn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("CoreDBAPI.Model.Artiklar", b =>
                {
                    b.HasOne("CoreDBAPI.Model.Kategori", "Kategori")
                        .WithMany("Artiklars")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("CoreDBAPI.Model.Kategori", b =>
                {
                    b.Navigation("Artiklars");
                });
#pragma warning restore 612, 618
        }
    }
}
